apiVersion: batch/v1
kind: Job
metadata:
  name: aggregator
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: aggregator
        image: kafka-aggregator:latest
        imagePullPolicy: IfNotPresent
