apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 20
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: worker
        imagePullPolicy: Always
        image: asia-northeast1-docker.pkg.dev/distributed-task-471604/distributed-task-repo/kafka-consumer:latest
