apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 20
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: worker
        imagePullPolicy: IfNotPresent
        image: kafka-consumer:latest
