apiVersion: batch/v1
kind: Job
metadata:
  name: producer
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: producer
        image: kafka-producer:latest
        imagePullPolicy: IfNotPresent
